# Generated by Django 2.2.28 on 2022-11-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fraudreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, null=True)),
                ('mobileNumber', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('postingDate', models.DateTimeField(auto_now_add=True)),
                ('assignedTime', models.CharField(max_length=200, null=True)),
                ('updationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=100, null=True)),
                ('teamLeaderName', models.CharField(max_length=100, null=True)),
                ('teamMobno', models.CharField(max_length=20, null=True)),
                ('teamMembers', models.CharField(max_length=200, null=True)),
                ('postingDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('postingDate', models.DateTimeField(auto_now_add=True)),
                ('fraudreport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ReportSystem.Fraudreport')),
            ],
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='assignTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ReportSystem.Team'),
        ),
    ]
