# Generated by Django 2.2.28 on 2022-11-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fraudreport',
            table='fraudreport',
        ),
    ]
